
namespace PkMn.Model.Enums
{
    public enum MoveEffectType
    {
        CancelEnemyMove,
        Charge,
        Copy,
        CustomDamage,
        Disable,
        EndWildBattle,
        IgnoreSemiInvulnerability,
        IgnoreTypeEffectiveness,
        IgnoreTypeImmunity,
        LeechSeed,
        LockInMove,
        MirrorMove,
        MissDamage,
        MultiHit,
        MustBeFaster,
        NeverDeductPP,
        NoEffect,
        None,
        OneHitKO,
        PayDay,
        PerfectAccuracy,
        ProtectStatStages,
        Random,
        RecoilDamage,
        ResetStatStages,
        ResetStatus,
        RestoreHealth,
        SemiInvulnerable,
        Stat,
        Status,
        StatusRequirement,
        Substitute,
        TransferHealth
    }
}
